name: build-ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: daniestevez/gr-satellites-ci-action@v0.1.4
